spring.application.name=MultiMarket

# DATABASE CONFIGURATION (MICROSOFT SQL SERVER - SQLEXPRESS)
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=multimarket_db;encrypt=true;trustServerCertificate=true;integratedSecurity=true;
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# HIBERNATE / JPA CONFIGURATION
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

# SPRING SECURITY
logging.level.org.springframework.security=INFO

# SPRING CLOUD / FEIGN
spring.cloud.compatibility-verifier.enabled=false
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
